VALID_EMAIL_REGEX: '\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z'
regex: '\A0\d{9,10}\z'
name_max_length: 50
email_max_length: 255
min_password_length: 6
digit_10: 10
digit_12: 12
digit_15: 15
digit_50: 50
digit_255: 255
avatar:
  size_30: 30
  size: 80
  list_size: 50
users_per_page: 20
books_per_page: 20
status:
  banned: 1
  active: 0
day_7: 7
day_5: 5
mailer_from: "noreply@example.com"
number_5: 5
b: 6
book_per_row: 4
authors_per_page: 10
time_format: "%Y-%m-%d %H:%M:%S"
favourite_books_home: 4
number_1: 1
number_20: 20
created_time_format: "%Y-%m-%d"
type_img: "PNG, JPG"
number_0: 0
number_255: 255
number_500: 500
