VALID_EMAIL_REGEX: '\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z'
name_max_length: 50
email_max_length: 255
min_password_length: 6
digit_10: 10
digit_12: 12
digit_15: 15
digit_50: 50
digit_255: 255
avatar:
  size_30: 30
  size: 80
  list_size: 50
users_per_page: 10
books_per_page: 10
status:
  banned: 1
  active: 0
day_7: 7
day_5: 5
mailer_from: "noreply@example.com"
number_5: 5
b: 6
book_per_row: 4
authors_per_page: 10
time_format: "%Y-%m-%d %H:%M:%S"
favourite_books_home: 4
number_20: 20
number_1: 1
